export const POLICY_EFFECTIVE_DATE = "2026년 10월 1일";
export const PROMOTION_START_DATE = "2026년 10월 1일";
export const PROMOTION_END_DATE = "2027년 9월 30일";

export const POLICY_EFFECTIVE_DATE_LABEL = POLICY_EFFECTIVE_DATE;
export const PROMOTION_PERIOD_LABEL =
  `${PROMOTION_START_DATE} ~ ${PROMOTION_END_DATE}`;
