export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type MenuSiteStatus = "draft" | "published" | "archived";
export type MenuSectionKey = "set_menu" | "main_menu" | "dessert_drink";
export type SupportedLocale = "ko" | "en" | "zh" | "ja";
export type BadgeType = "none" | "recommend" | "popular" | "best" | "discount" | "event" | "signature";
export type OrderStatus = "pending" | "paid" | "cancelled" | "refunded";
export type PaymentStatus = "ready" | "paid" | "failed" | "cancelled";
export type InquiryStatus = "open" | "answered" | "closed";

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          phone: string | null;
          company_name: string | null;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          phone?: string | null;
          company_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string | null;
          display_name?: string | null;
          phone?: string | null;
          company_name?: string | null;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      admin_users: {
        Row: {
          user_id: string;
          memo: string | null;
          created_at: string;
        };
        Insert: {
          user_id: string;
          memo?: string | null;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          memo?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      menu_sites: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          slug: string;
          template_key: string;
          template_category: string | null;
          status: MenuSiteStatus;
          description: string | null;
          brand_description: string | null;
          intro_title: string | null;
          intro_description: string | null;
          menu_cover_title: string | null;
          menu_cover_description: string | null;
          menu_cover_label: string | null;
          about_description: string | null;
          opening_hours: string | null;
          map_url: string | null;
          logo_url: string | null;
          logo_path: string | null;
          cover_image_url: string | null;
          cover_image_path: string | null;
          brand_color: string | null;
          business_name: string | null;
          business_address: string | null;
          business_phone: string | null;
          restaurant_name: string | null;
          restaurant_category: string | null;
          restaurant_type: string | null;
          restaurant_address: string | null;
          restaurant_phone: string | null;
          instagram_url: string | null;
          notes: string | null;
          settings: Json;
          design_settings: Json;
          page_settings: Json;
          published_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          slug: string;
          template_key?: string;
          template_category?: string | null;
          status?: MenuSiteStatus;
          description?: string | null;
          brand_description?: string | null;
          intro_title?: string | null;
          intro_description?: string | null;
          menu_cover_title?: string | null;
          menu_cover_description?: string | null;
          menu_cover_label?: string | null;
          about_description?: string | null;
          opening_hours?: string | null;
          map_url?: string | null;
          logo_url?: string | null;
          logo_path?: string | null;
          cover_image_url?: string | null;
          cover_image_path?: string | null;
          brand_color?: string | null;
          business_name?: string | null;
          business_address?: string | null;
          business_phone?: string | null;
          restaurant_name?: string | null;
          restaurant_category?: string | null;
          restaurant_type?: string | null;
          restaurant_address?: string | null;
          restaurant_phone?: string | null;
          instagram_url?: string | null;
          notes?: string | null;
          settings?: Json;
          design_settings?: Json;
          page_settings?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          slug?: string;
          template_key?: string;
          template_category?: string | null;
          status?: MenuSiteStatus;
          description?: string | null;
          brand_description?: string | null;
          intro_title?: string | null;
          intro_description?: string | null;
          menu_cover_title?: string | null;
          menu_cover_description?: string | null;
          menu_cover_label?: string | null;
          about_description?: string | null;
          opening_hours?: string | null;
          map_url?: string | null;
          logo_url?: string | null;
          logo_path?: string | null;
          cover_image_url?: string | null;
          cover_image_path?: string | null;
          brand_color?: string | null;
          business_name?: string | null;
          business_address?: string | null;
          business_phone?: string | null;
          restaurant_name?: string | null;
          restaurant_category?: string | null;
          restaurant_type?: string | null;
          restaurant_address?: string | null;
          restaurant_phone?: string | null;
          instagram_url?: string | null;
          notes?: string | null;
          settings?: Json;
          design_settings?: Json;
          page_settings?: Json;
          published_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_pages: {
        Row: {
          id: string;
          menu_site_id: string;
          title: string;
          description: string | null;
          description_visible: boolean;
          legacy_section_key: string | null;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          title: string;
          description?: string | null;
          description_visible?: boolean;
          legacy_section_key?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          title?: string;
          description?: string | null;
          description_visible?: boolean;
          legacy_section_key?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_categories: {
        Row: {
          id: string;
          menu_site_id: string;
          menu_page_id: string | null;
          name: string;
          description: string | null;
          description_visible: boolean;
          section_key: MenuSectionKey;
          sort_order: number;
          visible: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          menu_page_id?: string | null;
          name: string;
          description?: string | null;
          description_visible?: boolean;
          section_key?: MenuSectionKey;
          sort_order?: number;
          visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          menu_page_id?: string | null;
          name?: string;
          description?: string | null;
          description_visible?: boolean;
          section_key?: MenuSectionKey;
          sort_order?: number;
          visible?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_items: {
        Row: {
          id: string;
          menu_site_id: string;
          category_id: string | null;
          name: string;
          set_name: string | null;
          description: string | null;
          price: number;
          price_label: string | null;
          portion_label: string | null;
          price_visible: boolean;
          portion_visible: boolean;
          traits_visible: boolean;
          image_url: string | null;
          image_path: string | null;
          badge: string | null;
          badge_label: string | null;
          badge_type: BadgeType | null;
          recommended: boolean;
          origin_info: string | null;
          is_best: boolean;
          is_sold_out: boolean;
          visible: boolean;
          sort_order: number;
          options: Json;
          allergens: Json;
          translations: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          category_id?: string | null;
          name: string;
          set_name?: string | null;
          description?: string | null;
          price?: number;
          price_label?: string | null;
          portion_label?: string | null;
          price_visible?: boolean;
          portion_visible?: boolean;
          traits_visible?: boolean;
          image_url?: string | null;
          image_path?: string | null;
          badge?: string | null;
          badge_label?: string | null;
          badge_type?: BadgeType | null;
          recommended?: boolean;
          origin_info?: string | null;
          is_best?: boolean;
          is_sold_out?: boolean;
          visible?: boolean;
          sort_order?: number;
          options?: Json;
          allergens?: Json;
          translations?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          category_id?: string | null;
          name?: string;
          set_name?: string | null;
          description?: string | null;
          price?: number;
          price_label?: string | null;
          portion_label?: string | null;
          price_visible?: boolean;
          portion_visible?: boolean;
          traits_visible?: boolean;
          image_url?: string | null;
          image_path?: string | null;
          badge?: string | null;
          badge_label?: string | null;
          badge_type?: BadgeType | null;
          recommended?: boolean;
          origin_info?: string | null;
          is_best?: boolean;
          is_sold_out?: boolean;
          visible?: boolean;
          sort_order?: number;
          options?: Json;
          allergens?: Json;
          translations?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_item_price_options: {
        Row: {
          id: string;
          menu_site_id: string;
          menu_item_id: string;
          label: string;
          price: number | null;
          price_label: string | null;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          menu_item_id: string;
          label: string;
          price?: number | null;
          price_label?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          menu_item_id?: string;
          label?: string;
          price?: number | null;
          price_label?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      menu_item_traits: {
        Row: {
          id: string;
          menu_site_id: string;
          menu_item_id: string;
          label: string;
          value: number;
          max_value: number;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          menu_item_id: string;
          label: string;
          value?: number;
          max_value?: number;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          menu_item_id?: string;
          label?: string;
          value?: number;
          max_value?: number;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_events: {
        Row: {
          id: string;
          menu_site_id: string;
          event_title: string | null;
          event_subtitle: string | null;
          event_description: string | null;
          event_period: string | null;
          event_image_url: string | null;
          event_image_path: string | null;
          event_benefit: string | null;
          event_detail: string | null;
          event_regular_price_label: string | null;
          event_sale_price_label: string | null;
          event_price_visible: boolean;
          start_date: string | null;
          end_date: string | null;
          link_url: string | null;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          event_title?: string | null;
          event_subtitle?: string | null;
          event_description?: string | null;
          event_period?: string | null;
          event_image_url?: string | null;
          event_image_path?: string | null;
          event_benefit?: string | null;
          event_detail?: string | null;
          event_regular_price_label?: string | null;
          event_sale_price_label?: string | null;
          event_price_visible?: boolean;
          start_date?: string | null;
          end_date?: string | null;
          link_url?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          event_title?: string | null;
          event_subtitle?: string | null;
          event_description?: string | null;
          event_period?: string | null;
          event_image_url?: string | null;
          event_image_path?: string | null;
          event_benefit?: string | null;
          event_detail?: string | null;
          event_regular_price_label?: string | null;
          event_sale_price_label?: string | null;
          event_price_visible?: boolean;
          start_date?: string | null;
          end_date?: string | null;
          link_url?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_chefs: {
        Row: {
          id: string;
          menu_site_id: string;
          chef_name: string;
          chef_role: string | null;
          chef_description: string | null;
          chef_image_url: string | null;
          chef_image_path: string | null;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          chef_name: string;
          chef_role?: string | null;
          chef_description?: string | null;
          chef_image_url?: string | null;
          chef_image_path?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          chef_name?: string;
          chef_role?: string | null;
          chef_description?: string | null;
          chef_image_url?: string | null;
          chef_image_path?: string | null;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_social_links: {
        Row: {
          id: string;
          menu_site_id: string;
          type: string;
          label: string | null;
          display_name: string | null;
          url: string;
          visible: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          type: string;
          label?: string | null;
          display_name?: string | null;
          url: string;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          type?: string;
          label?: string | null;
          display_name?: string | null;
          url?: string;
          visible?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_site_translations: {
        Row: {
          id: string;
          menu_site_id: string;
          locale: SupportedLocale;
          restaurant_name: string | null;
          restaurant_category: string | null;
          brand_description: string | null;
          intro_title: string | null;
          intro_description: string | null;
          menu_cover_title: string | null;
          menu_cover_description: string | null;
          about_description: string | null;
          opening_hours: string | null;
          restaurant_address: string | null;
          restaurant_phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          menu_site_id: string;
          locale: SupportedLocale;
          restaurant_name?: string | null;
          restaurant_category?: string | null;
          brand_description?: string | null;
          intro_title?: string | null;
          intro_description?: string | null;
          menu_cover_title?: string | null;
          menu_cover_description?: string | null;
          about_description?: string | null;
          opening_hours?: string | null;
          restaurant_address?: string | null;
          restaurant_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          menu_site_id?: string;
          locale?: SupportedLocale;
          restaurant_name?: string | null;
          restaurant_category?: string | null;
          brand_description?: string | null;
          intro_title?: string | null;
          intro_description?: string | null;
          menu_cover_title?: string | null;
          menu_cover_description?: string | null;
          about_description?: string | null;
          opening_hours?: string | null;
          restaurant_address?: string | null;
          restaurant_phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_category_translations: {
        Row: {
          id: string;
          category_id: string;
          locale: SupportedLocale;
          name: string | null;
          description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          category_id: string;
          locale: SupportedLocale;
          name?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          category_id?: string;
          locale?: SupportedLocale;
          name?: string | null;
          description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_item_translations: {
        Row: {
          id: string;
          item_id: string;
          locale: SupportedLocale;
          name: string | null;
          description: string | null;
          price_label: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          item_id: string;
          locale: SupportedLocale;
          name?: string | null;
          description?: string | null;
          price_label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          item_id?: string;
          locale?: SupportedLocale;
          name?: string | null;
          description?: string | null;
          price_label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_chef_translations: {
        Row: {
          id: string;
          chef_id: string;
          locale: SupportedLocale;
          chef_name: string | null;
          chef_role: string | null;
          chef_description: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          chef_id: string;
          locale: SupportedLocale;
          chef_name?: string | null;
          chef_role?: string | null;
          chef_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          chef_id?: string;
          locale?: SupportedLocale;
          chef_name?: string | null;
          chef_role?: string | null;
          chef_description?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_event_translations: {
        Row: {
          id: string;
          event_id: string;
          locale: SupportedLocale;
          event_title: string | null;
          event_subtitle: string | null;
          event_description: string | null;
          event_period: string | null;
          event_benefit: string | null;
          event_detail: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          locale: SupportedLocale;
          event_title?: string | null;
          event_subtitle?: string | null;
          event_description?: string | null;
          event_period?: string | null;
          event_benefit?: string | null;
          event_detail?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          locale?: SupportedLocale;
          event_title?: string | null;
          event_subtitle?: string | null;
          event_description?: string | null;
          event_period?: string | null;
          event_benefit?: string | null;
          event_detail?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      menu_social_link_translations: {
        Row: {
          id: string;
          social_link_id: string;
          locale: SupportedLocale;
          label: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          social_link_id: string;
          locale: SupportedLocale;
          label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          social_link_id?: string;
          locale?: SupportedLocale;
          label?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      orders: {
        Row: {
          id: string;
          user_id: string;
          menu_site_id: string | null;
          product_key: string | null;
          template_key: string | null;
          order_name: string | null;
          payment_id: string | null;
          customer_name: string | null;
          buyer_name: string | null;
          buyer_phone: string | null;
          buyer_email: string | null;
          business_name: string | null;
          business_number: string | null;
          raw_payload: Json | null;
          status: OrderStatus;
          total_amount: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          menu_site_id?: string | null;
          product_key?: string | null;
          template_key?: string | null;
          order_name?: string | null;
          payment_id?: string | null;
          customer_name?: string | null;
          buyer_name?: string | null;
          buyer_phone?: string | null;
          buyer_email?: string | null;
          business_name?: string | null;
          business_number?: string | null;
          raw_payload?: Json | null;
          status?: OrderStatus;
          total_amount?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          menu_site_id?: string | null;
          product_key?: string | null;
          template_key?: string | null;
          order_name?: string | null;
          payment_id?: string | null;
          customer_name?: string | null;
          buyer_name?: string | null;
          buyer_phone?: string | null;
          buyer_email?: string | null;
          business_name?: string | null;
          business_number?: string | null;
          raw_payload?: Json | null;
          status?: OrderStatus;
          total_amount?: number;
          created_at?: string;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          order_id: string | null;
          product_key: string | null;
          template_key: string | null;
          payment_id: string | null;
          portone_payment_id: string | null;
          status: PaymentStatus;
          amount: number;
          raw_payload: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          order_id?: string | null;
          product_key?: string | null;
          template_key?: string | null;
          payment_id?: string | null;
          portone_payment_id?: string | null;
          status?: PaymentStatus;
          amount?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          order_id?: string | null;
          product_key?: string | null;
          template_key?: string | null;
          payment_id?: string | null;
          portone_payment_id?: string | null;
          status?: PaymentStatus;
          amount?: number;
          raw_payload?: Json | null;
          created_at?: string;
        };
        Relationships: [];
      };
      inquiries: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          status: InquiryStatus;
          admin_reply: string | null;
          replied_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          status?: InquiryStatus;
          admin_reply?: string | null;
          replied_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          status?: InquiryStatus;
          admin_reply?: string | null;
          replied_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
