export const CAFE_DESIGN_A_STITCH_SAMPLE = {
  site: {
    restaurant_name: "AUBE COFFEE",
    restaurant_category: "카페",
    restaurant_type: "cafe",
    menu_cover_label: "SPECIALTY COFFEE",
    intro_title: "AUBE COFFEE",
    intro_description: "신선한 스페셜티 원두와 유기농 재료로 건강하고 다채로운 맛을 제안합니다.",
    brand_description: "오브 커피는 신선한 스페셜티 원두와 유기농 재료를 사용하여 건강하고 다채로운 맛을 제안하는 모던 카페 브랜드입니다.",
    menu_cover_title: "AUBE COFFEE",
    menu_cover_description: "신선한 스페셜티 원두와 유기농 재료를 사용하여 건강하고 다채로운 맛을 제안하는 모던 카페 브랜드입니다.",
    about_description: "정돈된 메뉴와 시그니처 음료를 중심으로 선명한 카페 경험을 제안합니다.",
    opening_hours: "매일 10:00 - 21:00",
    restaurant_address: "서울시 예시구 오브로 12",
    restaurant_phone: "02-0000-0000",
    cover_image_url: "/menu-templates/cafe_design_a/basil-featured.jpg",
    settings: {
      footer_notice_1: "Wi-Fi AUBE_GUEST · PW 1234-5678",
      footer_notice_2: "Instagram @aube_coffee",
      footer_notice_3: "",
    },
  },
  pages: [
    {
      title: "메뉴 페이지 1",
      legacy_section_key: "main_menu",
      categories: [
        {
          name: "SIGNATURE COFFEE",
          items: [
            {
              name: "바질 크림 라떼",
              set_name: "BASIL CREAM LATTE",
              price: 6500,
              price_label: "6.5",
              description: "생바질로 만든 수제 크림이 올라간 아인슈페너 스타일",
              image_url: "/menu-templates/cafe_design_a/basil-featured.jpg",
              badge_label: "SIGNATURE",
              recommended: true,
            },
            {
              name: "오트 너티 라떼",
              set_name: "OAT NUTTY LATTE",
              price: 6800,
              price_label: "6.8",
              description: "고소한 귀리 우유와 구운 견과류 블렌딩",
              badge_label: "BEST",
            },
            {
              name: "흑임자 크림 라떼",
              set_name: "BLACK SESAME LATTE",
              price: 6500,
              price_label: "6.5",
              description: "진한 흑임자 크림이 올라간 시그니처 라떼",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 6500, price_label: "6.5" }],
            },
            {
              name: "솔티드 카라멜 라떼",
              set_name: "SALTED CARAMEL LATTE",
              price: 6500,
              price_label: "6.5",
              description: "단짠 조화가 좋은 카라멜 라떼",
            },
          ],
        },
        {
          name: "CLASSIC COFFEE",
          items: [
            {
              name: "아메리카노",
              set_name: "AMERICANO",
              price: 4500,
              price_label: "4.5",
              description: "깔끔한 산미와 고소한 밸런스",
            },
            {
              name: "카페 라떼",
              set_name: "CAFE LATTE",
              price: 5500,
              price_label: "5.5",
              description: "부드러운 우유와 에스프레소",
            },
            {
              name: "바닐라 빈 라떼",
              set_name: "VANILLA BEAN LATTE",
              price: 6000,
              price_label: "6.0",
              description: "마다가스카르 바닐라의 은은한 단맛",
            },
            {
              name: "플랫 화이트",
              set_name: "FLAT WHITE",
              price: 5000,
              price_label: "5.0",
              description: "진한 에스프레소와 촘촘한 밀크폼",
              portion_label: "HOT ONLY",
              price_options: [{ label: "HOT ONLY", price: 5000, price_label: "5.0" }],
            },
            {
              name: "콜드브루",
              set_name: "COLD BREW",
              price: 5000,
              price_label: "5.0",
              description: "천천히 추출한 부드러운 콜드브루",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 5000, price_label: "5.0" }],
            },
          ],
        },
        {
          name: "NON-COFFEE",
          section_key: "dessert_drink",
          items: [
            {
              name: "제주 말차 라떼",
              set_name: "JEJU MATCHA LATTE",
              price: 6000,
              price_label: "6.0",
              description: "제주산 유기농 말차의 진한 풍미",
              badge_label: "BEST",
            },
            {
              name: "밀크티 보틀",
              set_name: "MILK TEA BOTTLE",
              price: 6500,
              price_label: "6.5",
              description: "24시간 냉침한 수제 밀크티",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 6500, price_label: "6.5" }],
            },
            {
              name: "발로나 초코 라떼",
              set_name: "VALRHONA CHOCO LATTE",
              price: 6500,
              price_label: "6.5",
              description: "진한 발로나 초콜릿의 깊은 풍미",
            },
            {
              name: "딸기 라떼",
              set_name: "STRAWBERRY LATTE",
              price: 6500,
              price_label: "6.5",
              description: "생딸기 과육이 씹히는 달콤한 라떼",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 6500, price_label: "6.5" }],
              badge_label: "NEW",
            },
          ],
        },
        {
          name: "TEA & ADE",
          section_key: "dessert_drink",
          items: [
            {
              name: "레몬 바질 에이드",
              set_name: "LEMON BASIL ADE",
              price: 6000,
              price_label: "6.0",
              description: "생레몬즙과 바질의 청량함",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 6000, price_label: "6.0" }],
              badge_label: "BEST",
            },
            {
              name: "자몽 블랙티 에이드",
              set_name: "GRAPEFRUIT BLACK TEA ADE",
              price: 6000,
              price_label: "6.0",
              description: "자몽과 블랙티의 산뜻한 조화",
              portion_label: "ICE ONLY",
              price_options: [{ label: "ICE ONLY", price: 6000, price_label: "6.0" }],
            },
            {
              name: "유기농 캐모마일",
              set_name: "ORGANIC CHAMOMILE",
              price: 5000,
              price_label: "5.0",
              description: "은은한 꽃향이 편안한 허브티",
              portion_label: "HOT ONLY",
              price_options: [{ label: "HOT ONLY", price: 5000, price_label: "5.0" }],
            },
            {
              name: "얼그레이 리저브",
              set_name: "EARL GREY RESERVE",
              price: 5500,
              price_label: "5.5",
              description: "베르가못 향이 선명한 클래식 티",
            },
          ],
        },
        {
          name: "BAKERY",
          section_key: "dessert_drink",
          items: [
            {
              name: "클래식 버터 스콘",
              set_name: "CLASSIC BUTTER SCONE",
              price: 4500,
              price_label: "4.5",
              description: "프랑스산 고메버터 풍미",
            },
            {
              name: "무화과 휘낭시에",
              set_name: "FIG FINANCIER",
              price: 3500,
              price_label: "3.5",
              description: "무화과의 달콤함과 버터 풍미",
            },
            {
              name: "솔티 초코 휘낭시에",
              set_name: "SALTY CHOCO FINANCIER",
              price: 3800,
              price_label: "3.8",
              description: "짭짤한 초콜릿과 촉촉한 구움과자",
              badge_label: "NEW",
            },
            {
              name: "레몬 파운드 케이크",
              set_name: "LEMON POUND CAKE",
              price: 4500,
              price_label: "4.5",
              description: "상큼한 레몬 아이싱",
            },
          ],
        },
        {
          name: "DESSERT",
          section_key: "dessert_drink",
          items: [
            {
              name: "흑임자 바스크 치즈케이크",
              set_name: "SESAME CHEESECAKE",
              price: 7500,
              price_label: "7.5",
              description: "진한 흑임자 크림치즈 케이크",
            },
            {
              name: "티라미수 롤",
              set_name: "TIRAMISU ROLL",
              price: 6500,
              price_label: "6.5",
              description: "마스카포네 크림과 커피 향",
            },
            {
              name: "시즌 과일 타르트",
              set_name: "SEASONAL FRUIT TART",
              price: 8000,
              price_label: "8.0",
              description: "제철 과일과 바삭한 타르트지",
            },
          ],
        },
      ],
    },
  ],
} as const;
