const CAFE_A_MATCHA_FEATURED_IMAGE = "/menu-templates/cafe_design_a/malcha_present.jpg";
const CAFE_A_NUTTY_FEATURED_IMAGE = "/menu-templates/cafe_design_a/nutty-cream-featured.jpg";
const REAL_MATCHA_ACCENT = "#2AA36D";

export const CAFE_DESIGN_A_STITCH_SAMPLE = {
  site: {
    restaurant_name: "REAL MATCHA",
    restaurant_category: "카페",
    restaurant_type: "cafe",
    menu_cover_label: "MATCHA & COFFEE",
    intro_title: "REAL MATCHA",
    intro_description: "제주 맛차의 선명한 향과 부드러운 크림을 현대적으로 풀어낸 맛차 카페입니다.",
    brand_description: "리얼 맛차는 좋은 제주 맛차를 중심으로 커피와 베이커리를 균형 있게 제안하는 모던 카페입니다.",
    menu_cover_title: "REAL MATCHA",
    menu_cover_description: "제주 맛차의 선명한 향과 부드러운 크림을 현대적으로 풀어낸 맛차 카페입니다.",
    about_description: "맛차의 깊이와 크림의 부드러움을 한 잔에 담습니다.",
    opening_hours: "매일 10:00 - 21:00",
    restaurant_address: "서울시 예시구 맛차로 12",
    restaurant_phone: "02-0000-0000",
    cover_image_url: CAFE_A_MATCHA_FEATURED_IMAGE,
    settings: {
      footer_notice_1: "Wi-Fi REAL_MATCHA · PW 1234-5678",
      footer_notice_2: "Instagram @real.matcha",
      footer_notice_3: "",
    },
  },
  featured_slides: [
    {
      id: "real-matcha-featured-cream-latte",
      image_url: CAFE_A_MATCHA_FEATURED_IMAGE,
      image_path: null,
      featured_item_key: "real-matcha-cream-latte",
      featured_item_name: "리얼 맛차 크림 라떼",
      sort_order: 0,
    },
    {
      id: "real-matcha-featured-nutty-cream-latte",
      image_url: CAFE_A_NUTTY_FEATURED_IMAGE,
      image_path: null,
      featured_item_key: "nutty-cream-latte",
      featured_item_name: "너티 크림 라떼",
      sort_order: 1,
    },
    {
      id: "real-matcha-featured-deep-matcha-cloud",
      image_url: CAFE_A_MATCHA_FEATURED_IMAGE,
      image_path: null,
      featured_item_key: "deep-matcha-cloud",
      featured_item_name: "딥 맛차 클라우드",
      sort_order: 2,
    },
  ],
  time_sales: [
    {
      key: "americano-morning-deal",
      name: "아메리카노 모닝딜",
      schedule_type: "once",
      badge_text: "모닝딜",
      badge_background_color: REAL_MATCHA_ACCENT,
      time_display_mode: "message",
      time_display_text: "매일 오전 8시부터 10시까지",
      targets: [{ target_item_key: "americano", target_item_name: "아메리카노", sale_price: 2500 }],
    },
    {
      key: "classic-butter-scone-closeout",
      name: "클래식 버터 스콘 재고 마감",
      schedule_type: "once",
      duration_minutes: 60,
      badge_text: "재고 마감",
      badge_background_color: REAL_MATCHA_ACCENT,
      time_display_mode: "countdown",
      targets: [{ target_item_key: "classic-butter-scone", target_item_name: "클래식 버터 스콘", sale_price: 2200 }],
    },
  ],
  widgets: [],
  mixed_content_order: [
    { block_type: "category", page_key: "main-menu", category_key: "signature-coffee", sort_order: 0 },
    { block_type: "category", page_key: "main-menu", category_key: "classic-coffee", sort_order: 1 },
    { block_type: "category", page_key: "main-menu", category_key: "non-coffee", sort_order: 2 },
    { block_type: "category", page_key: "main-menu", category_key: "ade", sort_order: 3 },
    { block_type: "category", page_key: "main-menu", category_key: "bakery", sort_order: 4 },
  ],
  pages: [
    {
      key: "main-menu",
      title: "메뉴 페이지 1",
      legacy_section_key: "main_menu",
      categories: [
        {
          key: "signature-coffee",
          name: "MATCHA SIGNATURE",
          items: [
            {
              key: "real-matcha-cream-latte",
              name: "리얼 맛차 크림 라떼",
              set_name: "REAL MATCHA CREAM LATTE",
              price: 5800,
              description: "제주 맛차와 부드러운 크림을 진하게 즐기는 시그니처 라떼",
              badge_label: "SIGNATURE",
              recommended: true,
              price_note: "ICE ONLY",
            },
            {
              key: "nutty-cream-latte",
              name: "너티 크림 라떼",
              set_name: "NUTTY CREAM LATTE",
              price: 5500,
              description: "고소한 견과 크림과 에스프레소의 부드러운 조화",
              badge_label: "BEST",
              recommended: true,
              price_note: "ICE ONLY",
            },
            {
              key: "deep-matcha-cloud",
              name: "딥 맛차 클라우드",
              set_name: "DEEP MATCHA CLOUD",
              price: 5900,
              description: "짙은 맛차 라떼 위에 가벼운 크림을 올린 한 잔",
              price_note: "ICE ONLY",
            },
          ],
        },
        {
          key: "classic-coffee",
          name: "CLASSIC COFFEE",
          items: [
            {
              key: "americano",
              name: "아메리카노",
              set_name: "AMERICANO",
              price: 3500,
              description: "깔끔한 산미와 고소한 밸런스",
            },
            {
              key: "cafe-latte",
              name: "카페 라떼",
              set_name: "CAFE LATTE",
              price: 4300,
              description: "부드러운 우유와 에스프레소",
            },
            {
              key: "flat-white",
              name: "플랫화이트",
              set_name: "FLAT WHITE",
              price: 4800,
              description: "진한 에스프레소와 촘촘한 밀크폼",
            },
            {
              key: "vanilla-bean-latte",
              name: "바닐라 빈 라떼",
              set_name: "VANILLA BEAN LATTE",
              price: 5300,
              description: "바닐라 빈의 은은한 단맛을 더한 라떼",
            },
          ],
        },
        {
          key: "non-coffee",
          name: "NON-COFFEE",
          section_key: "dessert_drink",
          items: [
            {
              key: "valrhona-choco-latte",
              name: "발로나 초코 라떼",
              set_name: "VALRHONA CHOCO LATTE",
              price: 5500,
              description: "진한 발로나 초콜릿의 깊은 풍미",
            },
            {
              key: "jeju-matcha-latte",
              name: "제주 맛차 라떼",
              set_name: "JEJU MATCHA LATTE",
              price: 5700,
              description: "쌉싸름한 제주 맛차와 부드러운 우유",
            },
            {
              key: "earl-grey-milk-tea",
              name: "얼그레이 밀크티",
              set_name: "EARL GREY MILK TEA",
              price: 5700,
              description: "베르가못 향과 우유가 어우러진 밀크티",
            },
          ],
        },
        {
          key: "ade",
          name: "ADE",
          section_key: "dessert_drink",
          items: [
            {
              key: "lemon-basil-ade",
              name: "레몬 바질 에이드",
              set_name: "LEMON BASIL ADE",
              price: 5500,
              description: "생레몬즙과 바질의 청량함",
              price_note: "ICE ONLY",
            },
            {
              key: "grapefruit-rosemary-ade",
              name: "자몽 로즈마리 에이드",
              set_name: "GRAPEFRUIT ROSEMARY ADE",
              price: 5800,
              description: "생자몽과 로즈마리 향의 산뜻한 조화",
              price_note: "ICE ONLY",
            },
            {
              key: "green-grape-mint-ade",
              name: "청포도 민트 에이드",
              set_name: "GREEN GRAPE MINT ADE",
              price: 5800,
              description: "청포도의 달콤함과 민트의 청량함",
              price_note: "ICE ONLY",
            },
          ],
        },
        {
          key: "bakery",
          name: "BAKERY",
          section_key: "dessert_drink",
          items: [
            {
              key: "classic-butter-scone",
              name: "클래식 버터 스콘",
              set_name: "CLASSIC BUTTER SCONE",
              price: 3200,
              description: "프랑스산 고메버터 풍미",
            },
            {
              key: "lemon-madeleine",
              name: "레몬 마들렌",
              set_name: "LEMON MADELEINE",
              price: 3000,
              description: "레몬 향을 담아 촉촉하게 구운 마들렌",
            },
            {
              key: "chocolate-financier",
              name: "초콜릿 휘낭시에",
              set_name: "CHOCOLATE FINANCIER",
              price: 3500,
              description: "다크 초콜릿과 헤이즐넛의 깊은 풍미",
            },
            {
              key: "butter-croissant",
              name: "버터 크루아상",
              set_name: "BUTTER CROISSANT",
              price: 3800,
              description: "프랑스산 버터로 겹겹이 구운 크루아상",
            },
            {
              key: "matcha-terrine",
              name: "맛차 테린",
              set_name: "MATCHA TERRINE",
              price: 5800,
              description: "진한 제주 맛차를 꾸덕하게 구운 디저트",
            },
          ],
        },
      ],
    },
  ],
} as const;
