import type { MenuPageData } from "@/lib/menu-page-data";
import { DEFAULT_ENABLED_LOCALES, DEFAULT_LOCALE } from "@/lib/locales";
import {
  DEFAULT_MENU_PAGE_DISPLAY_SETTINGS,
  DEFAULT_PROMOTION_PAGE_DISPLAY_SETTINGS,
  serializeMenuPageDisplaySettings,
} from "@/lib/display-page-settings";
import { getDefaultPageSettings } from "@/types/menu";

const now = "2026-06-03T00:00:00.000Z";
const siteId = "template-preview-display-menu-a";

function pageId(index: number) {
  return `${siteId}-page-${index}`;
}

function categoryId(pageIndex: number, categoryIndex: number) {
  return `${siteId}-category-${pageIndex}-${categoryIndex}`;
}

function itemId(pageIndex: number, categoryIndex: number, itemIndex: number) {
  return `${siteId}-item-${pageIndex}-${categoryIndex}-${itemIndex}`;
}

export function buildDisplayMenuAPreviewData(): MenuPageData {
  const pageSettings = getDefaultPageSettings();

  return {
    locale: DEFAULT_LOCALE,
    enabledLocales: [...DEFAULT_ENABLED_LOCALES],
    publicServiceType: "screen",
    menuSite: {
      id: siteId,
      user_id: "template-preview",
      name: "Display Menu A",
      slug: "preview-display-menu-a",
      template_key: "display_menu_a",
      template_category: "display",
      status: "published",
      description: "디스플레이 메뉴보드 미리보기",
      logo_url: null,
      cover_image_url: null,
      intro_image_url: null,
      brand_color: "#101513",
      business_name: "AUBE COFFEE",
      business_address: "서울시 예시구 오브로 12",
      business_phone: "02-0000-0000",
      restaurant_name: "AUBE COFFEE",
      restaurant_category: "카페",
      restaurant_type: "cafe",
      restaurant_address: "서울시 예시구 오브로 12",
      restaurant_phone: "02-0000-0000",
      intro_title: null,
      intro_description: null,
      brand_description: "좋은 원두와 정성스러운 디저트로 일상에 작은 여유를 더하는 카페입니다.",
      menu_cover_label: null,
      menu_cover_title: null,
      menu_cover_description: null,
      about_description: null,
      opening_hours: "매일 10:00 - 21:00",
      map_url: null,
      page_settings: pageSettings,
      settings: {},
    },
    pageSettings,
    pages: [
      {
        id: pageId(0),
        title: "전체 메뉴",
        description: "디스플레이 화면에 맞춰 메뉴와 가격을 크게 보여줍니다.",
        description_visible: true,
        display_settings: serializeMenuPageDisplaySettings(DEFAULT_MENU_PAGE_DISPLAY_SETTINGS),
        legacy_section_key: null,
        visible: true,
        sort_order: 0,
        created_at: now,
      },
      {
        id: pageId(1),
        title: "시그니처 추천",
        description: "이미지와 메뉴 목록을 함께 보여주는 분할형 예시입니다.",
        description_visible: true,
        display_settings: serializeMenuPageDisplaySettings({
          ...DEFAULT_MENU_PAGE_DISPLAY_SETTINGS,
          menuLayoutType: "split_image_menu",
          splitImage: {
            url: "/placeholders/starter/cafe-a-cover.png",
            path: null,
            title: "오늘의 시그니처",
            description: "바질 크림 라떼와 시즌 디저트를 함께 추천합니다.",
            position: "left",
          },
        }),
        legacy_section_key: null,
        visible: true,
        sort_order: 1,
        created_at: now,
      },
      {
        id: pageId(2),
        title: "이미지 프로모션",
        description: null,
        description_visible: false,
        display_settings: serializeMenuPageDisplaySettings({
          ...DEFAULT_PROMOTION_PAGE_DISPLAY_SETTINGS,
          promotion: {
            ...DEFAULT_PROMOTION_PAGE_DISPLAY_SETTINGS.promotion,
            title: "MATCHA WEEK",
            description: "제주 말차 라떼와 말차 디저트를 한 주 동안 특별하게 만나보세요.",
            mediaType: "image",
            mediaUrl: "/placeholders/starter/cafe-a-cover.png",
            mediaPath: null,
          },
        }),
        legacy_section_key: null,
        visible: true,
        sort_order: 2,
        created_at: now,
      },
      {
        id: pageId(3),
        title: "영상 프로모션",
        description: null,
        description_visible: false,
        display_settings: serializeMenuPageDisplaySettings({
          ...DEFAULT_PROMOTION_PAGE_DISPLAY_SETTINGS,
          promotion: {
            ...DEFAULT_PROMOTION_PAGE_DISPLAY_SETTINGS.promotion,
            title: "BREW MOMENT",
            description: "매장에서 흘러가는 짧은 영상 프로모션 예시입니다.",
            mediaType: "video",
            mediaUrl: null,
            mediaPath: null,
            videoUrl: "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
          },
        }),
        legacy_section_key: null,
        visible: true,
        sort_order: 3,
        created_at: now,
      },
    ],
    categories: [
      {
        id: categoryId(0, 0),
        menu_page_id: pageId(0),
        name: "SIGNATURE COFFEE",
        description: null,
        description_visible: true,
        sort_order: 1,
        visible: true,
      },
      {
        id: categoryId(0, 1),
        menu_page_id: pageId(0),
        name: "CLASSIC COFFEE",
        description: null,
        description_visible: true,
        sort_order: 2,
        visible: true,
      },
      {
        id: categoryId(0, 2),
        menu_page_id: pageId(0),
        name: "DESSERT",
        description: null,
        description_visible: true,
        sort_order: 3,
        visible: true,
      },
      {
        id: categoryId(1, 0),
        menu_page_id: pageId(1),
        name: "RECOMMENDED",
        description: null,
        description_visible: true,
        sort_order: 1,
        visible: true,
      },
    ],
    items: [
      {
        id: itemId(0, 0, 0),
        category_id: categoryId(0, 0),
        name: "바질 크림 라떼",
        set_name: "BASIL CREAM LATTE",
        description: "생바질로 만든 수제 크림이 올라간 시그니처 라떼",
        price: 6500,
        price_label: "6.5",
        price_visible: true,
        portion_label: "ICE ONLY",
        portion_visible: true,
        image_url: null,
        badge: "SIGNATURE",
        badge_label: "SIGNATURE",
        badge_type: null,
        recommended: true,
        origin_info: null,
        is_best: true,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 1,
      },
      {
        id: itemId(0, 0, 1),
        category_id: categoryId(0, 0),
        name: "오트 너티 라떼",
        set_name: "OAT NUTTY LATTE",
        description: "고소한 귀리 우유와 구운 견과류 블렌딩",
        price: 6500,
        price_label: "6.5",
        price_visible: true,
        portion_label: "HOT / ICE",
        portion_visible: true,
        image_url: null,
        badge: "BEST",
        badge_label: "BEST",
        badge_type: null,
        recommended: true,
        origin_info: null,
        is_best: true,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 2,
      },
      {
        id: itemId(0, 0, 2),
        category_id: categoryId(0, 0),
        name: "흑임자 크림 라떼",
        set_name: "BLACK SESAME LATTE",
        description: "진한 흑임자 크림이 올라간 고소한 라떼",
        price: 6500,
        price_label: "6.5",
        price_visible: true,
        portion_label: "ICE",
        portion_visible: true,
        image_url: null,
        badge: null,
        badge_label: null,
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 3,
      },
      {
        id: itemId(0, 1, 0),
        category_id: categoryId(0, 1),
        name: "아메리카노",
        set_name: "AMERICANO",
        description: "",
        price: 4500,
        price_label: "4.5",
        price_visible: true,
        portion_label: "HOT / ICE",
        portion_visible: true,
        image_url: null,
        badge: null,
        badge_label: null,
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 1,
      },
      {
        id: itemId(0, 1, 1),
        category_id: categoryId(0, 1),
        name: "카페 라떼",
        set_name: "CAFE LATTE",
        description: "",
        price: 5000,
        price_label: "5.0",
        price_visible: true,
        portion_label: "HOT / ICE",
        portion_visible: true,
        image_url: null,
        badge: null,
        badge_label: null,
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 2,
      },
      {
        id: itemId(0, 1, 2),
        category_id: categoryId(0, 1),
        name: "카라멜 마키아토",
        set_name: "CARAMEL MACCHIATO",
        description: "진한 에스프레소와 달콤한 카라멜의 조화",
        price: 6000,
        price_label: "6.0",
        price_visible: true,
        portion_label: "HOT / ICE",
        portion_visible: true,
        image_url: null,
        badge: null,
        badge_label: null,
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 3,
      },
      {
        id: itemId(0, 2, 0),
        category_id: categoryId(0, 2),
        name: "흑임자 바스크 치즈케이크",
        set_name: "SESAME CHEESECAKE",
        description: "진한 흑임자 크림치즈 케이크",
        price: 7500,
        price_label: "7.5",
        price_visible: true,
        portion_label: null,
        portion_visible: false,
        image_url: null,
        badge: null,
        badge_label: null,
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 1,
      },
      {
        id: itemId(0, 2, 1),
        category_id: categoryId(0, 2),
        name: "시즌 과일 타르트",
        set_name: "SEASONAL FRUIT TART",
        description: "계절 과일과 바닐라 크림을 올린 타르트",
        price: 8000,
        price_label: "8.0",
        price_visible: true,
        portion_label: null,
        portion_visible: false,
        image_url: null,
        badge: "NEW",
        badge_label: "NEW",
        badge_type: null,
        recommended: false,
        origin_info: null,
        is_best: false,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 2,
      },
      {
        id: itemId(1, 0, 0),
        category_id: categoryId(1, 0),
        name: "바질 크림 라떼",
        set_name: "BASIL CREAM LATTE",
        description: "생바질 크림과 진한 에스프레소가 어우러지는 인기 조합",
        price: 6500,
        price_label: "6.5",
        price_visible: true,
        portion_label: "ICE ONLY",
        portion_visible: true,
        image_url: null,
        badge: "SIGNATURE",
        badge_label: "SIGNATURE",
        badge_type: null,
        recommended: true,
        origin_info: null,
        is_best: true,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 1,
      },
      {
        id: itemId(1, 0, 1),
        category_id: categoryId(1, 0),
        name: "제주 말차 라떼",
        set_name: "JEJU MATCHA LATTE",
        description: "제주산 유기농 말차의 진한 풍미",
        price: 6000,
        price_label: "6.0",
        price_visible: true,
        portion_label: "HOT / ICE",
        portion_visible: true,
        image_url: null,
        badge: "BEST",
        badge_label: "BEST",
        badge_type: null,
        recommended: true,
        origin_info: null,
        is_best: true,
        is_sold_out: false,
        traits_visible: true,
        visible: true,
        sort_order: 2,
      },
    ],
    priceOptions: [],
    traits: [],
    events: [],
    chefs: [],
    socialLinks: [],
  };
}
